### ISSUE TITLE
Not working anymore.

### ISSUE THREAD

**Issue by deckameron** [IonRod/titanium-account-manager#1]
Hi @lonRod,
Thank you for creating this module. Unfortunately it is not working anymore.
This is the error.

[ERROR] :  art: dlopen("/data/app/com.project.pro-2/lib/arm/libcom.ionrod.accountmanager.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.ionrod.accountmanager.so"...
[ERROR] :  TiApplication: (KrollRuntimeThread) [50,65] Sending event: exception on thread: KrollRuntimeThread msg:java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.ionrod.accountmanager.so"...; Titanium 4.1.0,2015/03/06 15:04,0ddb63e
[ERROR] :  TiApplication: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__exidx_end" referenced by "libcom.ionrod.accountmanager.so"...
[ERROR] :  TiApplication:   at java.lang.Runtime.loadLibrary(Runtime.java:371)
[ERROR] :  TiApplication:   at java.lang.System.loadLibrary(System.java:989)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.runtime.v8.V8Runtime.loadExternalModules(V8Runtime.java:132)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:99)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:185)
[ERROR] :  TiApplication:   at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:109)

**Comment by IonRod** [comment]
Thanks for feedback!
Could you provide information about Titanium SDK version you are using?

**Comment by IonRod** [comment]
@deckameron 
To fix that issue you have to use Titanium SDK 3.5.0.GA. The bug is reprodused on 3.5.1.GA.

**Comment by lcmen** [comment]
@IonRod any plans to make it work with 3.5.1.GA?
